CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" varchar(10) UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" date NOT NULL,
  "rol_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "description" varchar NOT NULL,
  "teacher" int NOT NULL,
  "category_id" int NOT NULL,
  "level_id" int NOT NULL
);

CREATE TABLE "videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar UNIQUE NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "student_courses" (
  "student_id" int NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

ALTER TABLE "student_courses" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id");

ALTER TABLE "student_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");

ALTER TABLE "videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");



INSERT INTO roles (role) 
VALUES 
('Student'),
('Teacher'),
('Admin');

INSERT INTO categories (name) 
VALUES 
('Programming'),
('Maths');

INSERT INTO levels (name) 
VALUES 
('Beginner'),
('Intermediate'),
('Advanced');

INSERT INTO users (name, email, password, age, rol_id) 
VALUES 
('Carlos Narvaez', 'carlos@mail.com', '1234', '1987-12-11', 1),
('Ian Rosas', 'ian@mail.com', '5678', '1994-12-1', 2),
('Alejandra Olazagasti', 'alejandra@mail.com', 'abcd', '1990-2-4', 1);

INSERT INTO courses (title, description, teacher, category_id, level_id) 
VALUES 
('NodeJS Basics', 'Learn everything about Node', 2, 1, 1),
('JavaScript Mid', 'Learn everything about methods and how to use them', 2, 1, 2);

INSERT INTO videos (title, url, course_id) 
VALUES 
('Introduction to back-end', 'https://courses.node.com/one/', 1),
('Promises and asynchronous programming', 'https://courses.javascript/promisesasync/', 2);

INSERT INTO student_courses (student_id, course_id)
VALUES 
(1, 1),
(3, 2);
